export default {
  currentComponent: '',
  accessToken: '',
  formData: {},
  next: 'menu',
  now: '',
  reloaded: false,
  done: false,
  deal: false,
  tellerHome: '',
  ceftDeal: false,
  status: 0,
  dbu: '',
  fcbu: '',
  idbu: '',
  ifcbu: '',
  signed: true,
  product: 0,
  ceft: '',
  fundTransfer: '',
  username: '',
  key: '',
  cleint: '',
}
